In [3]:
import numpy as  np

using def 
 1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’


`Input`:
arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 7
foo_1(arr, target)

`Output`:
[2 3 4 5 6 8 7 1 9 0]


In [68]:
def foo1(arr):
    arr = np.array([3,8,7,7,7,7,7,8,7,10])
    if target not in arr:
        return "no item found"
        


In [69]:
count_of_values = np.argsort(np.abs(arr-7))

print("count of indies of 7 :",count_of_values)


count of indies of 7 : [2 3 4 5 6 8 1 7 9 0]


In [70]:
target=11

foo1(arr)   

'no item found'

3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array
data = np.arr([85,89,88], rows are students
              [78,89,94], column are subjects
              
              [91,87,90]
              [87,95,84]

In [79]:
data = np.array([
    [85,89,88],
    [78,89,94],
    [91,87,90],
    [87,95,84]
])
above_90_marks =np.any(data >90,axis =1)
result_array = data[above_90_marks]
print(result_array)

[[78 89 94]
 [91 87 90]
 [87 95 84]]


3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

data = np.array([
[120,150,130,110],
[200,180,220,250],
[90,100,95,110],
[300,280,320,340]])
   

In [1]:
def foo(sales_data):
    mean_values = np.mean(sales_data, axis=1)
    median_values = np.median(sales_data, axis=1)
    std_dev_values = np.std(sales_data, axis=1)
    highest_sales_month = np.max(sales_data, axis=1)
    for i in range(len(sales_data)):
        print(f"Product {i + 1}:")
        print(f"Mean: {mean_values[i]}")
        print(f"Median: {median_values[i]}")
        print(f"Standard Deviation: {std_dev_values[i]}")
        print(f"Month with Highest Sales: Month {highest_sales_month[i] + 1}")
        print()

In [4]:
sales_data=np.array([[120, 150, 130, 110],
            [200, 180, 220, 250],
            [90, 100, 95, 110],
            [300,280,320, 340]])

In [5]:
foo(sales_data)

Product 1:
Mean: 127.5
Median: 125.0
Standard Deviation: 14.79019945774904
Month with Highest Sales: Month 151

Product 2:
Mean: 212.5
Median: 210.0
Standard Deviation: 25.8602010819715
Month with Highest Sales: Month 251

Product 3:
Mean: 98.75
Median: 97.5
Standard Deviation: 7.39509972887452
Month with Highest Sales: Month 111

Product 4:
Mean: 310.0
Median: 310.0
Standard Deviation: 22.360679774997898
Month with Highest Sales: Month 341




3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.


In [105]:
a =np.random.randint(1,100,1000)

unique_values ,value_counts = np.unique(a,return_counts=True)
top_10_indices = np.argsort(value_counts)[::-1][:10]

top_10_values = unique_values[top_10_indices]
top_10_counts = value_counts[top_10_indices]

print(top_10_values, top_10_counts)

[ 3 60 48 47 31 99 37 97 72 78] [17 16 15 15 15 14 14 14 14 14]


## 2)
Write a user defined function foo_2 that takes a  2,3 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced without using


of non-zero elements wrt axis.


In [107]:
def foo_2(arr, axis):
    if arr.ndim != 2:
        print("Input array must be 2-dimensional.")
    else:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts

def foo_3(arr, axis):
    if arr.ndim != 3:
        print("Input array must be 3-dimensional.")
    else:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts

In [108]:
arr = np.array([[1, 2, 3, 4], [0, 5, 0, 0], [2, 0, 1, 0]])
foo_2(arr, axis=0)

In [ ]:
arr1 = np.array([[[1, 2, 3, 4], [0, 5, 0, 0], [2, 0, 1, 0]],
                 [[2, 0, 1, 0], [0, 5, 0, 0], [1, 2, 3, 4]]])

In [ ]:
foo_3(arr1,axis=0)

In [109]:
foo(sales_data)

Product 1:
Mean: 127.5
Median: 125.0
Standard Deviation: 14.79019945774904
Month with Highest Sales: Month 151

Product 2:
Mean: 212.5
Median: 210.0
Standard Deviation: 25.8602010819715
Month with Highest Sales: Month 251

Product 3:
Mean: 98.75
Median: 97.5
Standard Deviation: 7.39509972887452
Month with Highest Sales: Month 111

Product 4:
Mean: 310.0
Median: 310.0
Standard Deviation: 22.360679774997898
Month with Highest Sales: Month 341

